### ISSUE TITLE
The app crashes the second i open the storage on my switch

### ISSUE THREAD

**Issue by DuckersMcQuack** [retronx-team/mtp-server-nx#11]
I'm on system version 9 with AMD 0.9.4, and the app crashes when i open the storage on my pc. Both over usb C to A and C to C

**Comment by arantius** [comment]
Probably same.  Horizon 9.1.0, Atmosphere 0.10.1.  Launch mtp-server-nx, see "Press + to exit".  See "MTP Device" appear.  Open that and I see "sdcard" and an accurate free/total space summary.  Open *that* and mtp-server-nx crashes.  (This last time, I saw the "emuMMC" folder appear briefly before the explorer window closed, because the server crashed.)

Would love to provide more detail but I don't know what else to say.

**Comment by theboy181** [comment]
Same issue here! Please HALP 

Latest Hekate, Atmosphere FW 9.1.0 and KOSMOS

**Comment by TheLastZombie** [comment]
Same for me. I switched to [nxmtp](https://github.com/liuervehc/nxmtp) for now, hope this will be resolved soon.

**Comment by theboy181** [comment]
Looks like it also crashes on 9.1.0

Sent from my iPhone

On Feb 10, 2020, at 12:57 AM, TLZ <notifications@github.com> wrote:

﻿

Same for me. I switched to nxmtp<https://github.com/liuervehc/nxmtp> for now, hope this will be resolved soon.
