### ISSUE TITLE
Software closed because an error occured

### ISSUE THREAD

**Issue by RisingHopperZeroOne** [retronx-team/mtp-server-nx#4]
I am unable to access my sdcard as whenever I try to open it, it closes and gives me an error.

v1.1 with fw 8.1.0 with atmosphere v0.9.4 on emummc.
Error occurs with both applet and title redirection.

**Comment by designgears** [comment]
Can confirm

v1.1, 9.0.0, v0.9.4 sysnand

**Comment by m4xw** [comment]
Seems to happen with windows primarily.

**Comment by ckurtz22** [comment]
When attempting to test on Atmosphere 0.9.4 - HOS 9.0.0 with commit 364eb I get the following backtrace: https://pastebin.com/phMXXeaj

Unsure what the heck HID has to do with Windows - will continue debugging.

**Comment by ckurtz22** [comment]
Well based on the lines where it crashes with, it would seem some sort of memory corruption issue I guess? monkaS

**Comment by ckurtz22** [comment]
That seems to just be a bug from threading, when I remove that thread it definitely looks like some memory corruption is happening.

**Comment by ckurtz22** [comment]
![linux](https://user-images.githubusercontent.com/14020943/65120973-54603a80-d9a3-11e9-8f84-a1305eab6290.jpg)
![windows](https://user-images.githubusercontent.com/14020943/65120975-54603a80-d9a3-11e9-89ca-ccc5dc06716a.jpg)
Here is the difference between Linux and Windows when the OS requests the contents of a directory... Windows seems to be requesting the contents of objects that have handles out of range (12289, etc), and this is causing incorrect memory accesses. Can do a quick fix just checking the range of handle accesses, but want to try and find out first why Windows is so bad. (might be bad handling of some other MTP request for Windows)

(Note: the parameter being printed is just the object handle getting passed into getObjectList, I left out the other 2 parameters because they were irrelevant)

**Comment by ckurtz22** [comment]
https://github.com/retronx-team/mtp-server-nx/blob/master/source/MtpServer.cpp#L603
seems there was a note to fix this already. Windows MTP appears to be getting drunk and asking for object refs of object handle 0x3000 that doesn't exist. Will just do a somewhat hacky fix for now unless someone has better insight on what is happening.

**Comment by Adubbz** [comment]
It appears even with the proper fix for the above using your ``fix-windows`` branch, crashing is still occurring with Windows 10 and fw 9.0.0. Looking at the crash logs and comparing with the elf, it appears this is still likely a memory corruption issue of some kind.

[01569855307_010061d00db74000.log](https://github.com/retronx-team/mtp-server-nx/files/3674399/01569855307_010061d00db74000.log)

**Comment by m4xw** [comment]
@Adubbz As it turns out, the Android code is quite bugged, I don't even know why it properly works on any android device...

**Comment by ckurtz22** [comment]
Am working on troubleshooting this with someone else as I seem to be the only person who does not experience this issue. First glance it might possibly be an issue with the modifications for Switch support (although why it only now popped up I have no clue).

**Comment by ghost** [comment]
Yep, happening to me too. Might swap back to the old, old mtp app for now.

**Comment by Chr0n4s** [comment]
happens to me too

**Comment by rrebrick** [comment]
Confirming this issue as well. Windows 10.
